#!/bin/sh

# exit on failure
set -e

# save environment variables
export >> /etc/environment

# a command has been specified, run it
if [ ! -z "${1}" ]; then
	exec tini -g -- "$@"

# start runit services
else
	exec tini -g -- /usr/bin/runsvdir -P /etc/service
fi
