#!/bin/sh

export DNSMASQ_USER=${DNSMASQ_USER:-dnsmasq}
export DNSMASQ_GROUP=${DNSMASQ_GROUP:-nogroup}
export DNSMASQ_CONFDIR=${DNSMASQ_CONFDIR:-/etc/dnsmasq.d}
export DNSMASQ_DATADIR=${DNSMASQ_DATADIR:-/run/dnsmasq}

export HAPROXY_USER=${HAPROXY_USER:-haproxy}
export HAPROXY_GROUP=${HAPROXY_GROUP:-haproxy}
export HAPROXY_CONFDIR=${HAPROXY_CONFDIR:-/etc/haproxy}
export HAPROXY_DATADIR=${HAPROXY_DATADIR:-/run/haproxy}

export USE_AD_BLOCKER=${USE_AD_BLOCKER:-false}
