#!/bin/sh

# source environment variables
. /etc/default-environment

# wait for dnsmasq to be running
while [ ! -f ${DNSMASQ_DATADIR}/dnsmasq.pid -a -z "$(cat ${DNSMASQ_DATADIR}/dnsmasq.pid)" -a ! -d "/proc/$(cat ${DNSMASQ_DATADIR}/dnsmasq.pid)" ]; do
	echo "waiting for dnsmasq to be up ..."
	sleep .5
done

export DNSMASQ_PID_FILE=${DNSMASQ_DATADIR}/dnsmasq.pid
export DNSMASQ_HOSTS_FILE=/run/dnsmasq/hosts/docker

exec /usr/sbin/dalidock 2>&1
