#!/bin/sh

# source environment variables
. /etc/default-environment

# wait for dnsmasq to be running
while ! pidof dnsmasq >/dev/null 2>&1; do
	echo "waiting for dnsmasq to be up ..."
	sleep .5
done

export DNSMASQ_PID_FILE=${DNSMASQ_DATADIR}/dnsmasq.pid
export DNSMASQ_HOSTS_FILE=/run/dnsmasq/hosts/docker

exec /usr/sbin/dalidock 2>&1
